/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyzatorRouteImport } from './routes/analyzator'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HistoriaRouteImport } from './routes/historia'
import { Route as KriteriaRouteImport } from './routes/kriteria'
import { Route as NastaveniaRouteImport } from './routes/nastavenia'
import { Route as PomocRouteImport } from './routes/pomoc'
import { Route as SablonyRouteImport } from './routes/sablony'
import { Route as SandboxRouteImport } from './routes/sandbox'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzatorRoute = AnalyzatorRouteImport.update({
  id: '/analyzator',
  path: '/analyzator',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const KriteriaRoute = KriteriaRouteImport.update({
  id: '/kriteria',
  path: '/kriteria',
  getParentRoute: () => rootRouteImport,
} as any)
const NastaveniaRoute = NastaveniaRouteImport.update({
  id: '/nastavenia',
  path: '/nastavenia',
  getParentRoute: () => rootRouteImport,
} as any)
const PomocRoute = PomocRouteImport.update({
  id: '/pomoc',
  path: '/pomoc',
  getParentRoute: () => rootRouteImport,
} as any)
const SablonyRoute = SablonyRouteImport.update({
  id: '/sablony',
  path: '/sablony',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxRoute = SandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyzator': typeof AnalyzatorRoute
  '/auth': typeof AuthRoute
  '/historia': typeof HistoriaRoute
  '/kriteria': typeof KriteriaRoute
  '/nastavenia': typeof NastaveniaRoute
  '/pomoc': typeof PomocRoute
  '/sablony': typeof SablonyRoute
  '/sandbox': typeof SandboxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyzator': typeof AnalyzatorRoute
  '/auth': typeof AuthRoute
  '/historia': typeof HistoriaRoute
  '/kriteria': typeof KriteriaRoute
  '/nastavenia': typeof NastaveniaRoute
  '/pomoc': typeof PomocRoute
  '/sablony': typeof SablonyRoute
  '/sandbox': typeof SandboxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyzator': typeof AnalyzatorRoute
  '/auth': typeof AuthRoute
  '/historia': typeof HistoriaRoute
  '/kriteria': typeof KriteriaRoute
  '/nastavenia': typeof NastaveniaRoute
  '/pomoc': typeof PomocRoute
  '/sablony': typeof SablonyRoute
  '/sandbox': typeof SandboxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyzator'
    | '/auth'
    | '/historia'
    | '/kriteria'
    | '/nastavenia'
    | '/pomoc'
    | '/sablony'
    | '/sandbox'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyzator'
    | '/auth'
    | '/historia'
    | '/kriteria'
    | '/nastavenia'
    | '/pomoc'
    | '/sablony'
    | '/sandbox'
  id:
    | '__root__'
    | '/'
    | '/analyzator'
    | '/auth'
    | '/historia'
    | '/kriteria'
    | '/nastavenia'
    | '/pomoc'
    | '/sablony'
    | '/sandbox'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzatorRoute: typeof AnalyzatorRoute
  AuthRoute: typeof AuthRoute
  HistoriaRoute: typeof HistoriaRoute
  KriteriaRoute: typeof KriteriaRoute
  NastaveniaRoute: typeof NastaveniaRoute
  PomocRoute: typeof PomocRoute
  SablonyRoute: typeof SablonyRoute
  SandboxRoute: typeof SandboxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyzator': {
      id: '/analyzator'
      path: '/analyzator'
      fullPath: '/analyzator'
      preLoaderRoute: typeof AnalyzatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kriteria': {
      id: '/kriteria'
      path: '/kriteria'
      fullPath: '/kriteria'
      preLoaderRoute: typeof KriteriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nastavenia': {
      id: '/nastavenia'
      path: '/nastavenia'
      fullPath: '/nastavenia'
      preLoaderRoute: typeof NastaveniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pomoc': {
      id: '/pomoc'
      path: '/pomoc'
      fullPath: '/pomoc'
      preLoaderRoute: typeof PomocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sablony': {
      id: '/sablony'
      path: '/sablony'
      fullPath: '/sablony'
      preLoaderRoute: typeof SablonyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzatorRoute: AnalyzatorRoute,
  AuthRoute: AuthRoute,
  HistoriaRoute: HistoriaRoute,
  KriteriaRoute: KriteriaRoute,
  NastaveniaRoute: NastaveniaRoute,
  PomocRoute: PomocRoute,
  SablonyRoute: SablonyRoute,
  SandboxRoute: SandboxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
