/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyzatorRouteImport } from './routes/analyzator'
import { Route as KriteriaRouteImport } from './routes/kriteria'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzatorRoute = AnalyzatorRouteImport.update({
  id: '/analyzator',
  path: '/analyzator',
  getParentRoute: () => rootRouteImport,
} as any)
const KriteriaRoute = KriteriaRouteImport.update({
  id: '/kriteria',
  path: '/kriteria',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyzator': typeof AnalyzatorRoute
  '/kriteria': typeof KriteriaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyzator': typeof AnalyzatorRoute
  '/kriteria': typeof KriteriaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyzator': typeof AnalyzatorRoute
  '/kriteria': typeof KriteriaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analyzator' | '/kriteria'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analyzator' | '/kriteria'
  id: '__root__' | '/' | '/analyzator' | '/kriteria'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzatorRoute: typeof AnalyzatorRoute
  KriteriaRoute: typeof KriteriaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyzator': {
      id: '/analyzator'
      path: '/analyzator'
      fullPath: '/analyzator'
      preLoaderRoute: typeof AnalyzatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kriteria': {
      id: '/kriteria'
      path: '/kriteria'
      fullPath: '/kriteria'
      preLoaderRoute: typeof KriteriaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzatorRoute: AnalyzatorRoute,
  KriteriaRoute: KriteriaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
